Ids are automatically added to headings.
owlchester/kanka pull request #570
Opened 2022-12-30 20:16 UTC by spitfire305

2022-12-30 20:26 UTC, ilestis requested changes

2022-12-30 20:26 UTC, ilestis commented on app/Models/MiscModel.php
> +        //changes here?
Are you sure? :P

2023-01-02 16:38 UTC, spitfire305 commented on app/Models/MiscModel.php
> +        //changes here?
Turns out changes not there

2023-01-02 17:18 UTC, ilestis approved these changes

2023-01-02 17:18 UTC, merged