Post Layouts Phase 5
owlchester/kanka pull request #709
Opened 2023-07-24 18:25 UTC by spitfire305

2023-07-24 21:09 UTC, ilestis requested changes

2023-07-24 21:09 UTC, ilestis commented on app/Services/EntityService.php
> +            ->whereNot('post_layouts.entity_type_id', '=', null)
Can be replaced by `whereNotNull()` I think

2023-07-24 21:09 UTC, ilestis commented on database/seeders/PostLayoutTableSeeder.php
>              DB::table('post_layouts')->insert([
Check your database. I have a lot of duplicates created each time I run `sail artisan db:seed`, which Kanka prod does with every release

2023-07-25 23:58 UTC, spitfire305 commented on resources/views/entities/components/_post_layouts.blade.php
> +            $rows = $entity->child
I dont think it makes sense to implement this into a scope, since elements() is a relationship.

2023-07-25 23:58 UTC, spitfire305 commented on resources/views/entities/components/_post_layouts.blade.php
> +            $elements = $entity->child
I dont think it makes sense to implement this into a scope, since elements() is a relationship.

2023-07-26 19:38 UTC, merged