Inventory phase 2
owlchester/kanka pull request #873
Opened 2024-05-10 20:41 UTC by spitfire305

2024-05-12 15:07 UTC, ilestis requested changes
Does this work well with emojis and & signs in the position field?

2024-05-12 15:07 UTC, ilestis commented on resources/js/tags.js
> +                    let $span = $("<span class='block grow text-left'>" + item.text + "</span>");
We need any of the html (the whole templateResult function can probably be removed), since positions have no colour option

2024-05-12 15:07 UTC, ilestis commented on resources/js/tags.js
> +        $.each($('.position-dropdown'), function () {
Since the function is called initTags, let's have this foreach come after the already existing one  for clarity :)

2024-05-12 15:07 UTC, ilestis commented on resources/views/entities/pages/inventory/_form.blade.php
>              'list' => 'position-list',
list is no longer needed. Does maxlength work here? I've never seen maxlength on a select field, but we must make sure user don't write a position with 200 letters that custs off

2024-05-12 15:07 UTC, ilestis commented on app/Http/Controllers/Entity/InventoryController.php
> +        $positions = Inventory::positionList($campaign)->pluck('position')->all();
It's only showing 20 results when the ticket specified to limit it to 50

2024-05-13 03:36 UTC, spitfire305 commented
> Does this work well with emojis and & signs in the position field?

Yeah, but emojis are cringe

2024-05-13 14:59 UTC, ilestis approved these changes

2024-05-13 14:59 UTC, merged